# Classification of Odoo 20 release-note items: CE / partial / EE.
# status: ce | partial | ee ;  conf: H (code evidence) | M (module-level) | L (educated guess, check!)
# p = probe regexes (git grep -i -E) run against CE clone and EE-only modules to collect evidence.

SECTION_DEFAULTS = {
    # section: (status, conf, ce_modules, ee_modules)
    "General": ("ce", "L", ["web"], []),
    "Technical": ("ce", "M", ["base", "mail"], []),
    "Industries": ("ee", "M", [], []),  # refined per module by industry dependency check
    "Accounting": ("ce", "L", ["account"], []),
    "Localizations": ("partial", "L", [], []),  # refined per country by module inventory
    "AI": ("ee", "H", [], ["ai", "ai_agentic"]),
    "Appointments": ("ee", "H", [], ["appointment"]),
    "Appraisals": ("ee", "H", [], ["hr_appraisal"]),
    "Attendances": ("ce", "M", ["hr_attendance"], []),
    "Barcode": ("ee", "H", [], ["stock_barcode"]),
    "Blog": ("ce", "M", ["website_blog"], []),
    "Calendar": ("ce", "M", ["calendar"], []),
    "Contacts": ("ce", "M", ["contacts", "base"], []),
    "CRM": ("ce", "M", ["crm"], []),
    "Dashboards": ("ce", "L", ["spreadsheet_dashboard", "spreadsheet"], []),
    "Discuss": ("ce", "M", ["mail"], []),
    "Documents": ("ee", "H", [], ["documents"]),
    "eCommerce": ("ce", "M", ["website_sale"], []),
    "eLearning": ("ce", "M", ["website_slides"], []),
    "Email Marketing": ("ce", "M", ["mass_mailing"], []),
    "Employees": ("ce", "M", ["hr"], []),
    "ESG": ("ee", "H", [], ["esg"]),
    "Events": ("ce", "M", ["event", "website_event"], []),
    "Expenses": ("ce", "M", ["hr_expense"], []),
    "Field Service": ("ee", "H", [], ["planning"]),
    "Fleet": ("ce", "M", ["fleet"], []),
    "Frontdesk": ("ee", "H", [], ["frontdesk"]),
    "Helpdesk": ("ee", "H", [], ["helpdesk"]),
    "Inventory": ("ce", "M", ["stock"], []),
    "Knowledge": ("ee", "H", [], ["knowledge"]),
    "Live Chat": ("ce", "M", ["im_livechat"], []),
    "Maintenance": ("ce", "M", ["maintenance"], []),
    "Manufacturing": ("ce", "M", ["mrp"], []),
    "Marketing Automation": ("ee", "H", [], ["marketing_automation"]),
    "Marketing Card": ("ce", "M", ["marketing_card"], []),
    "Online Payments": ("ce", "M", ["payment"], []),
    "Payroll": ("ee", "H", [], ["hr_payroll"]),
    "Phone": ("ee", "H", [], ["voip"]),
    "Planning": ("ee", "H", [], ["planning"]),
    "PLM": ("ee", "H", [], ["mrp_plm"]),
    "Point of Sale": ("ce", "M", ["point_of_sale"], []),
    "Project": ("ce", "M", ["project"], []),
    "Purchase": ("ce", "M", ["purchase"], []),
    "Quality": ("ee", "H", [], ["quality_control"]),
    "Recruitment": ("ce", "M", ["hr_recruitment"], []),
    "Referrals": ("ee", "H", [], ["hr_referral"]),
    "Rental": ("ee", "H", [], ["sale_renting"]),
    "Repairs": ("ce", "M", ["repair"], []),
    "Sales": ("ce", "M", ["sale"], []),
    "Shop Floor": ("ee", "H", [], ["mrp_workorder"]),
    "Sign": ("ee", "H", [], ["sign"]),
    "Social Marketing": ("ee", "H", [], ["social"]),
    "Spreadsheet": ("partial", "M", ["spreadsheet"], ["spreadsheet_edition"]),
    "Studio": ("ee", "H", [], ["web_studio"]),
    "Subscriptions": ("ee", "H", [], ["sale_subscription"]),
    "Time Off": ("ce", "M", ["hr_holidays"], []),
    "Timesheets": ("ce", "M", ["hr_timesheet"], []),
    "Website": ("ce", "M", ["website"], []),
    "WhatsApp": ("ee", "H", [], ["whatsapp"]),
}

SPREADSHEET_NOTE = ("Engine feature: o-spreadsheet ships LGPL in the CE `spreadsheet` module (used read-only by CE "
                    "dashboards), but creating/editing spreadsheets needs EE `spreadsheet_edition`. CE users can get "
                    "editing via OCA `spreadsheet_oca` (reporting-engine) once migrated.")

O = {
    # ---------------- General ----------------
    0: dict(s="ce", ce=["mail"], p=[r"Schedule Activity"]),
    1: dict(s="ce", ce=["web"], n="Calendar view side panel (CE web); 'Scheduling' option of Gantt is EE", p=[r"unschedul"]),
    2: dict(s="ce", ce=["mail"], p=[r"email_cc", r"partner_cc"]),
    3: dict(s="ce", ce=["mail"], p=[r"chatter.*filter|filter.*chatter"]),
    4: dict(s="ce", ce=["web"], p=[r"currency.*rate.*date|rate_date"]),
    5: dict(s="ce", ce=["web", "base"], p=[r"decimal.separator"]),
    6: dict(s="ce", ce=["web"]),
    7: dict(s="ce", ce=["digest"], p=[r"kpi_"]),
    8: dict(s="ce", ce=["base", "web"], p=[r"download.*attachments|attachments.*zip"]),
    9: dict(s="ce", ce=["mail"]),
    10: dict(s="ce", ce=["web"]),
    11: dict(s="ce", ce=["web"], n="Share-target of the web app (PWA) - verify which targets exist in CE (bills/expenses digitization needs EE OCR)", p=[r"share_target"]),
    12: dict(s="ee", ee=["web_gantt"], n="Gantt view is EE-only (`web_gantt`). OCA: web_timeline / project_timeline"),
    13: dict(s="ce", ce=["base_import", "product"]),
    14: dict(s="ce", ce=["web"], p=[r"\+=|-=.*duration"]),
    15: dict(s="ce", ce=["product", "stock", "mrp"]),
    16: dict(s="ce", ce=["website", "mail"], p=[r"link.preview"]),
    17: dict(s="ce", ce=["web"]),
    18: dict(s="ce", ce=["web"]),
    19: dict(s="partial", ce=["mail_plugin", "crm_mail_plugin", "project_mail_plugin"], ee=["helpdesk_mail_plugin"], n="Plugin backend for contacts/leads/tasks is CE; helpdesk tickets need EE Helpdesk"),
    20: dict(s="ee", ee=["web_map"], n="Map view is EE-only (`web_map`). OCA: web_view_leaflet_map"),
    21: dict(s="ce", ce=["web"], p=[r"material.symbols|MaterialSymbols"]),
    22: dict(s="partial", ce=["web"], ee=["web_enterprise"], n="Home-menu dashboard & mobile app login are EE (`web_enterprise`/mobile app); bottom-sheet date picker & touch forms are CE `web`", p=[r"bottom.?sheet"]),
    23: dict(s="ce", ce=["web"]),
    24: dict(s="ce", ce=["base", "account"], p=[r"partner.*identifier|identifier_type"]),
    25: dict(s="ce", ce=["mysubscription"], n="Module is LGPL in CE but only meaningful for databases with an odoo.com subscription"),
    26: dict(s="ce", ce=["web"], p=[r"offline"]),
    27: dict(s="ce", ce=["partner_autocomplete"], n="IAP service (credits)"),
    28: dict(s="ce", ce=["mail"], p=[r"pinned_at"]),
    29: dict(s="ce", ce=["portal"]),
    30: dict(s="ce", ce=["web"]),
    31: dict(s="ce", ce=["web"]),
    32: dict(s="ce", ce=["html_editor"]),
    33: dict(s="ce", ce=["product"]),
    34: dict(s="ee", ee=["delivery_sendcloud"], n="Sendcloud connector is EE. OCA: delivery-carrier repo"),
    35: dict(s="ce", ce=["base"], p=[r"ir\.model\.access.*domain|domain_force"]),
    36: dict(s="ce", ce=["web"]),
    37: dict(s="ce", ce=["account", "sale", "purchase"], p=[r"tax_calculation|price_include_override|Tax Included"]),
    38: dict(s="ce", ce=["sms"]),
    39: dict(s="ce", ce=["base", "web"], p=[r"Translation Mode"]),
    40: dict(s="ce", ce=["web"]),
    41: dict(s="ce", ce=["mail"]),
    42: dict(s="ce", ce=["web"]),
    43: dict(s="partial", ce=["mail", "web"], ee=["mail_mobile"], n="Browser web-push is CE; mobile-app push (formerly Firebase/OCN) is EE `mail_mobile`"),
    44: dict(s="ce", ce=["mail"]),
    45: dict(s="ce", ce=["base"]),
    # ---------------- Accounting ----------------
    71: dict(s="ce", ce=["account"]),
    72: dict(s="partial", ce=["account"], ee=["account_accountant"], n="Write-off wizard is CE; the bank reconciliation widget is EE", p=[r"account\.reconcile\.wizard"]),
    73: dict(s="ee", ee=["account_reports"], n="Annual/financial reports are EE (`account_reports`). OCA: account_financial_report, mis_builder"),
    74: dict(s="ee", ee=["account_asset"], n="OCA: account_asset_management"),
    75: dict(s="partial", ce=["account"], ee=["account_accountant"], conf="L"),
    76: dict(s="ee", ee=["account_reports"]),
    77: dict(s="ee", ee=["account_online_synchronization"], n="Bank sync is an EE/IAP service. OCA: bank-statement-import"),
    78: dict(s="ce", ce=["account"], conf="L", p=[r"_predict_"]),
    79: dict(s="partial", ce=["account"], ee=["account_asset", "account_accountant"], conf="L"),
    80: dict(s="ce", ce=["account"]),
    81: dict(s="ce", ce=["account"], p=[r"hash.*cash|cash.*hash"]),
    82: dict(s="ce", ce=["account"]),
    83: dict(s="ee", ee=["account_reports"]),
    84: dict(s="ee", ee=["currency_rate_live"], n="OCA: currency_rate_update"),
    85: dict(s="partial", ce=["account"], ee=["account_followup"], conf="L", p=[r"invoice_reminder|reminder"]),
    86: dict(s="ce", ce=["account"], conf="L", p=[r"download.*zip|zip.*download"]),
    87: dict(s="ce", ce=["hr_expense"]),
    88: dict(s="ce", ce=["account"]),
    89: dict(s="ce", ce=["account"], p=[r"duplicate"]),
    90: dict(s="ee", ee=["account_inter_company_rules"], conf="L"),
    91: dict(s="ce", ce=["account"]),
    92: dict(s="partial", ce=["account", "purchase", "stock_account"], ee=["account_reports"], conf="L"),
    93: dict(s="partial", ce=["account"], ee=["documents_account"], n="Chatter attachments CE; Documents-app files EE"),
    94: dict(s="partial", ce=["account"], ee=["account_accountant"], n="Checkbox/logic in CE `account`; bank reconciliation view is EE"),
    95: dict(s="ee", ee=["account_reports"]),
    96: dict(s="ce", ce=["account"]),
    97: dict(s="ce", ce=["base"], p=[r"XCG"]),
    98: dict(s="partial", ce=["account"], ee=["account_accountant"], conf="L"),
    99: dict(s="ee", ee=["account_accountant"]),
    100: dict(s="ce", ce=["account_iso20022"], conf="L", p=[r"pain\.001"]),
    101: dict(s="ce", ce=["account"], p=[r"parent_id.*account\.account|account\.account.*parent_id"]),
    102: dict(s="ee", ee=["account_online_payment"], conf="L"),
    103: dict(s="ce", ce=["account_peppol", "account_edi_ubl_cii"], p=[r"\bgln\b|global_location"]),
    104: dict(s="ce", ce=["account"]),
    105: dict(s="ce", conf="L", p=[r"[Pp]rofessional.*(percent|%)"]),
    106: dict(s="ce", ce=["purchase", "account"], conf="L"),
    107: dict(s="ee", ee=["account_accountant"]),
    108: dict(s="ee", ee=["account_followup"], n="OCA: account_credit_control"),
    109: dict(s="ce", ce=["account"], p=[r"Reset to Draft"]),
    110: dict(s="ee", ee=["account_accountant"]),
    111: dict(s="ee", ee=["account_asset"], n="OCA: account_asset_management"),
    112: dict(s="ce", ce=["account"], conf="L"),
    113: dict(s="ce", ce=["account"]),
    114: dict(s="ce", ce=["stock_account", "account"], conf="L"),
    115: dict(s="ce", ce=["l10n_account_withholding_tax"]),
    # ---------------- Blog/Calendar/Contacts/CRM ----------------
    232: dict(s="ce"), 233: dict(s="ce"), 234: dict(s="ce"),
    235: dict(s="ce"), 236: dict(s="ce"),
    237: dict(s="ce", ce=["google_calendar", "microsoft_calendar"]),
    238: dict(s="ce", ce=["google_calendar"]),
    239: dict(s="ce", ce=["calendar"]),
    240: dict(s="ee", ee=["appointment"], n="Availability sharing links come from EE Appointments", conf="L"),
    241: dict(s="ce", ce=["calendar", "mail"]),
    242: dict(s="ce", ce=["calendar", "web"]),
    243: dict(s="ce", ce=["calendar"], conf="L"),
    244: dict(s="ee", ee=["appointment"]),
    245: dict(s="ce", ce=["google_calendar"]),
    246: dict(s="ce", ce=["partner_autocomplete"], n="IAP enrichment service (credits)", conf="L"),
    247: dict(s="ce", ce=["web_hierarchy", "contacts"]),
    248: dict(s="ce", ce=["base"]),
    249: dict(s="ce"),
    250: dict(s="ce", ce=["crm_iap_mine"], n="IAP service (credits)"),
    251: dict(s="ce"),
    252: dict(s="ee", ee=["sale_subscription"], n="Needs Subscriptions (EE). OCA: contract / subscription_oca"),
    # ---------------- Dashboards / Discuss ----------------
    253: dict(s="ee", ee=["timesheet_grid"], conf="L"),
    254: dict(s="ce", ce=["spreadsheet"], n="o-spreadsheet engine (CE); editing dashboards requires EE"),
    255: dict(s="ce", ce=["spreadsheet_dashboard"]),
    256: dict(s="ce", ce=["spreadsheet"]),
    257: dict(s="ee", ee=["spreadsheet_dashboard_edition"], conf="L"),
    258: dict(s="ce", ce=["spreadsheet_dashboard"], conf="L"),
    259: dict(s="ce", ce=["spreadsheet"]),
    260: dict(s="ee", ee=["voip"]),
    261: dict(s="ce", ce=["mail"], conf="L", p=[r"transcri"]),
    262: dict(s="ce"), 263: dict(s="ce"), 264: dict(s="ce"), 265: dict(s="ce"),
    # ---------------- eCommerce ----------------
    275: dict(s="ee", ee=["ai_website_sale"]),
    277: dict(s="ee", ee=["ai_website_sale"], conf="L"),
    280: dict(s="partial", ce=["website_sale"], ee=["sale_subscription"], n="Donations in cart are CE; recurring donations need Subscriptions (EE)"),
    282: dict(s="ce", ce=["loyalty", "website_sale_loyalty"]),
    285: dict(s="ce", ce=["sale_gelato"]),
    288: dict(s="ce", ce=["website_sale", "delivery"]),
    291: dict(s="ee", ee=["delivery_sendcloud"], n="CE module `website_sale_mondialrelay` removed; replacement is the EE Sendcloud connector. OCA: delivery-carrier"),
    306: dict(s="ce", ce=["website_sale"], conf="L"),
    311: dict(s="ee", ee=["whatsapp"]),
    # ---------------- Email marketing ----------------
    326: dict(s="ce", ce=["mass_mailing"], conf="L"),
    # ---------------- Employees / Expenses / Fleet ----------------
    329: dict(s="ee", ee=["hr_payroll"], n="Salary simulation is Payroll (EE)"),
    330: dict(s="ce", ce=["hr"]),
    331: dict(s="ce", ce=["resource", "hr"]),
    333: dict(s="ce", ce=["event_product", "sale"], conf="L"),
    334: dict(s="ce"), 335: dict(s="ce", conf="L"),
    336: dict(s="ee", ee=["hr_payroll_expense"], n="Salary rules = Payroll (EE)"),
    338: dict(s="ee", ee=["hr_payroll_fleet"], n="Payroll part is EE; fleet driver field itself is CE"),
    # ---------------- Inventory ----------------
    344: dict(s="ce", ce=["stock_fleet"]),
    346: dict(s="partial", ce=["stock"], ee=["account_inter_company_rules"], conf="L"),
    349: dict(s="ce", ce=["stock_landed_costs"]),
    352: dict(s="ee", ee=["stock_barcode"]),
    355: dict(s="ee", ee=["delivery_sendcloud"]),
    356: dict(s="ee", ee=["delivery_sendcloud"]),
    359: dict(s="ce", ce=["stock"], conf="L"),
    364: dict(s="ce", ce=["stock"]),
    # ---------------- Live chat / Maintenance ----------------
    366: dict(s="ee", conf="L", p=[r"messenger|instagram"]),
    367: dict(s="ee", ee=["mrp_maintenance", "maintenance_enterprise"], n="Gantt views are EE (`web_gantt`)", conf="L"),
    # ---------------- Manufacturing ----------------
    381: dict(s="partial", ce=["mrp"], ee=["mrp_workorder", "stock_barcode_mrp"], n="Single Produce button in CE Manufacturing; Shop Floor/Barcode parts EE"),
    384: dict(s="ee", ee=["mrp_workorder"]),
    389: dict(s="ee", ee=["mrp_workorder"], n="Work Order Planning Gantt is EE"),
    391: dict(s="partial", ce=["mrp"], ee=["mrp_workorder"], n="Kanban view CE; Gantt planning EE"),
    # ---------------- POS ----------------
    469: dict(s="ee", ee=["pos_appointment"], conf="L"),
    474: dict(s="ee", ee=["pos_urban_piper"], conf="L"),
    475: dict(s="ee", ee=["pos_urban_piper"], conf="L"),
    476: dict(s="ce", ce=["pos_mercado_pago"]),
    487: dict(s="partial", ce=["pos_self_order", "pos_sms"], ee=["pos_whatsapp"], n="SMS receipt CE; WhatsApp EE", conf="L"),
    # ---------------- Project / Purchase / Recruitment / Repairs ----------------
    492: dict(s="ee", ee=["project_enterprise"], n="Task schedule printing from Gantt (EE)"),
    493: dict(s="ce", ce=["project", "sale_project"], conf="L"),
    494: dict(s="ce", ce=["crm", "project"], conf="L"),
    504: dict(s="ee", ee=["quality_control"]),
    509: dict(s="ce", ce=["hr_recruitment_skills"]),
    # ---------------- Sales ----------------
    521: dict(s="ce", ce=["sale_commission"], conf="L", p=[r"commission"]),
    522: dict(s="ce", ce=["sale"], conf="L"),
    529: dict(s="ee", ee=["sale_lazada"]),
    531: dict(s="ce", ce=["sale_commission"], conf="L"),
    539: dict(s="ce", ce=["sale_edi_ubl"], conf="L"),
    547: dict(s="ee", ee=["sale_tiktok"]),
    # ---------------- Timesheets ----------------
    617: dict(s="ee", ee=["timesheet_grid"], conf="L", p=[r"activitywatch"]),
    618: dict(s="ee", ee=["timesheet_grid"], conf="L", p=[r"timer"]),
    619: dict(s="ee", ee=["timesheet_grid"]), 620: dict(s="ee", ee=["timesheet_grid"]), 621: dict(s="ee", ee=["timesheet_grid"]),
    # ---------------- Website ----------------
    624: dict(s="ee", ee=["ai_website"]),
    625: dict(s="ee", ee=["ai_website"]),
    627: dict(s="ee", ee=["website_appointment"]),
    661: dict(s="ce", ce=["website_crm_partner_assign"]),
    668: dict(s="partial", ce=["website"], ee=["ai_website"], n="srcset & pagination SEO in CE; AI SEO helper EE"),
    679: dict(s="partial", ce=["website"], ee=["ai_website"], n="AI-powered positioning choices depend on IAP/AI", conf="L"),
    681: dict(s="ce", ce=["website"], conf="L", p=[r"whatsapp"]),
    # ---------------- EE sections with CE parts ----------------
    223: dict(s="ce", ce=["stock"], n="Bulk lot/serial generation is available in CE Inventory too", conf="L"),
    230: dict(s="partial", ce=["stock"], ee=["stock_barcode"], n="Pre-encoding packages in CE Inventory; scanning in EE Barcode"),
    603: dict(s="ce", ce=["base_automation", "mail"], n="Automation rules are CE (`base_automation`); Studio just exposes them", conf="L"),
    612: dict(s="ee", ee=["sale_subscription"], n="Loyalty engine is CE (`loyalty`); subscription rewards need EE"),
    517: dict(s="ee", ee=["sale_renting"]),
}

# ---- iteration 1 corrections from code probes ----
_upd = {
    72: dict(s="ee", ee=["account_accountant"], conf="H", n="`account.reconcile.wizard` (write-off) lives in EE `account_accountant`"),
    78: dict(s="ee", ee=["account_accountant"], conf="M", n="Line prediction (`_predict_*`) is in EE `account_accountant`"),
    100: dict(s="ee", ee=["account_iso20022"], conf="H", n="PAIN/ISO20022 payment files are EE (`account_iso20022`). OCA: account_banking_sepa_credit_transfer (bank-payment)"),
    11: dict(s="ce", ce=["web", "account", "hr_expense", "project", "crm", "hr_holidays"], conf="H", n="PWA share-target is CE; OCR digitization of bills/expenses is EE (`*_extract`)"),
    26: dict(s="ce", ce=["web"], conf="M"),
    28: dict(s="ce", ce=["mail"], conf="H"),
    39: dict(s="ce", ce=["web", "website"], conf="H"),
    97: dict(s="ce", ce=["base"], conf="H"),
    101: dict(s="ce", ce=["account"], conf="H"),
    103: dict(s="ce", ce=["account_edi_ubl_cii", "account_peppol"], conf="H"),
    105: dict(s="ce", ce=["account"], conf="M"),
    81: dict(s="ce", ce=["account"], conf="H"),
    261: dict(s="partial", ce=["mail"], ee=["voip_ai", "ai"], conf="L", n="Call recording plumbing in CE `mail`; AI summaries are EE"),
    366: dict(s="ee", ee=["social_facebook", "social_instagram"], conf="M"),
    521: dict(s="ee", ee=["sale_commission"], conf="H", n="Commissions app is EE (`sale_commission`). OCA: commission / sale_commission (commission repo)"),
    531: dict(s="ee", ee=["sale_commission"], conf="H", n="OCA: commission repo"),
    617: dict(s="ee", ee=["timesheet_grid"], conf="H"),
    618: dict(s="ee", ee=["timer", "timesheet_grid"], conf="M", n="Timer is EE (`timer`). OCA: project_timesheet_time_control"),
    681: dict(s="ce", ce=["website"], conf="M"),
    77: dict(s="ee", ee=["account_online_synchronization"], conf="M", n="Bank synchronization is an EE/IAP service. OCA: bank-statement-import"),
    487: dict(s="partial", ce=["pos_self_order"], ee=["whatsapp_pos_self_order", "pos_enterprise_sms_whatsapp"], conf="M", n="WhatsApp and SMS receipts via EE modules"),
    474: dict(s="ee", ee=["pos_urban_piper"], conf="M"),
    475: dict(s="ee", ee=["pos_urban_piper"], conf="M"),
}
for _k, _v in _upd.items():
    O[_k] = {"p": O.get(_k, {}).get("p", []), "ev": O.get(_k, {}).get("ev", []), **_v}
O[77] = dict(s="ee", ee=[], conf="M", n="Bank synchronization is an Odoo-hosted service (no bank-sync module in the 20.0 source tarball). OCA: bank-statement-import")

# ---- iteration 2: runbot API + module-diff verification (CE runbot 126446809, 2026-09-25) ----
RB = "runbot CE (API): "
_upd2 = {
    41: dict(s="ce", ce=["mail", "mail_tracking"], conf="H",
             n="Tracking values are no longer stored by `mail`; the `mail.tracking.value` model moved to the new optional CE module `mail_tracking` "
               "(+ `mail_tracking_mass_mailing`, `mail_tracking_sms`). ⚠️ Same technical names as OCA `mail_tracking` / `mail_tracking_mass_mailing` (OCA/mail 18.0/19.0) — the OCA modules must be renamed for 20.0",
             ev=[RB + "model mail.tracking.value is provided by module mail_tracking", "module diff 19.0→20.0: mail_tracking, mail_tracking_mass_mailing, mail_tracking_sms are new CE modules",
                 "OCA index: mail_tracking and mail_tracking_mass_mailing exist in OCA/mail@18.0 and @19.0"]),
    101: dict(s="ce", ce=["account"], conf="H", n="`account.group` is gone; `account.account.parent_id` structures the chart and `code` is no longer required",
              ev=[RB + "model account.group absent", RB + "account.account.parent_id many2one(account.account) from module account; account.account.code required=False"]),
    91: dict(s="ce", ce=["account"], conf="H", n="`account.payment.state` values are now draft / paid / reconciled / canceled / rejected",
             ev=[RB + "account.payment.state selection = draft, paid, reconciled, canceled, rejected"]),
    357: dict(s="ce", ce=["stock"], conf="H", n="The `stock.return.picking` wizard model no longer exists", ev=[RB + "model stock.return.picking absent"]),
    375: dict(s="ce", ce=["mrp"], conf="H", n="Field `mrp.bom.consumption` removed; consumption is always flexible", ev=[RB + "field mrp.bom.consumption absent"]),
    519: dict(s="ce", ce=["repair"], conf="H", n="`repair.order.state` no longer has 'under_repair'", ev=[RB + "repair.order.state selection = draft, confirmed, done, cancel"]),
    524: dict(s="ce", ce=["sale"], conf="H", n="`sale.order.line.product_id` is optional unless the 'Mandatory Product' setting is on", ev=[RB + "sale.order.line.product_id required=False"]),
    413: dict(s="ce", ce=["payment"], conf="H", n="The `sofort` payment method record is gone", ev=[RB + "payment.method with code 'sofort' (active or not): 0 records"]),
    330: dict(s="ce", ce=["hr"], conf="H", n="`hr_homeworking`, `hr_homeworking_calendar` and `hr_holidays_homeworking` were removed; work locations per weekday now live in `hr`",
              ev=["module diff 19.0→20.0: hr_homeworking* removed", "CE source: addons/hr/models/hr_employee_location.py; hr.employee.<weekday>_location_id fields from hr"]),
    291: dict(s="ee", ee=["delivery_sendcloud"], conf="H", n="CE modules `website_sale_mondialrelay` and `delivery_mondialrelay` were removed; Mondial Relay now only via the EE Sendcloud connector. OCA: delivery-carrier",
              ev=["module diff 19.0→20.0: website_sale_mondialrelay, delivery_mondialrelay removed from CE"]),
    21: dict(s="ce", ce=["web"], conf="H", n="Font Awesome replaced by Material Symbols in the web client — custom views/templates using `fa fa-*` icons need checking",
             ev=["CE source: no 'fa fa-' left in addons/web/static/src/**/*.xml"]),
    39: dict(s="ce", ce=["test_translation_mode", "web"], conf="H", n="Shipped as CE module `test_translation_mode` (sic) — install it to get the translation mode"),
    494: dict(s="ce", ce=["crm_sale_project"], conf="H", n="New CE module `crm_sale_project`"),
    661: dict(s="ce", ce=["website_partnership"], conf="H", n="New CE module `website_partnership`"),
    496: dict(s="ce", ce=["purchase_alternative"], conf="H", n="Alternatives now in the new CE module `purchase_alternative` (split from `purchase_requisition`)"),
    87: dict(s="ce", ce=["hr_expense"], conf="M", n="Standalone 'Employee Expenses' menu removed; approved expenses create draft vendor bills in the expense journal"),
    113: dict(s="ce", ce=["account"], conf="M", n="A product/account default tax outside the invoice's fiscal position is dropped even without a mapping"),
    218: dict(s="ce", ce=["hr_attendance"], conf="M", n="Users without Attendances rights are blocked from the app"),
    616: dict(s="ce", ce=["hr_holidays"], conf="M", n="New 'No' access level for Time Off"),
    371: dict(s="ce", ce=["mrp"], conf="M", n="BoM overview columns merged, extra-cost field on BoM, BoM comparison"),
    471: dict(s="ce", ce=["pos_hr"], conf="M", n="POS employee access levels renamed; new restrictive 'Supervised' level"),
    493: dict(s="ce", ce=["project", "sale_project"], conf="L", n="Profitability panel removed from the project dashboard in favour of dedicated reports"),
    645: dict(s="ce", ce=["website", "website_event", "website_blog", "website_hr_recruitment"], conf="M", n="Sidebar 'Follow Us'/'Share' blocks replaced by standard snippets"),
    27: dict(s="ce", ce=["partner_autocomplete"], conf="M", n="IAP service; industry no longer written as partner tags"),
}
for _k, _v in _upd2.items():
    O[_k] = {"p": O.get(_k, {}).get("p", []), "ev": O.get(_k, {}).get("ev", []), **_v}

# ---- iteration 3: low-confidence items settled by code probes ----
_upd3 = {
    92: dict(s="ce", ce=["purchase", "account", "stock_account"], conf="M", n="Accrual actions (Bills To Receive, Billed Not Received…) are in CE purchase/account", p=[r"Bills To Receive|Billed Not Received"]),
    106: dict(s="ce", ce=["purchase", "account"], conf="H", p=[r"_match_purchase|unmatch"]),
    223: dict(s="ce", ce=["stock"], conf="H", n="Lot/serial generation is CE `stock`; Barcode adds scanning", p=[r"action_generate_lot|generate_serial|next_serial"]),
    232: dict(s="ce", ce=["website_blog"], conf="H", p=[r"o_wblog"]),
    233: dict(s="ce", ce=["website_blog"], conf="H", p=[r"Recommended Post|recommended_post"]),
    234: dict(s="ce", ce=["website_blog"], conf="M", p=[r"_cron_publish|scheduled.*post"]),
    235: dict(s="ce", ce=["calendar"], conf="M"),
    236: dict(s="ce", ce=["calendar"], conf="M"),
    243: dict(s="ce", ce=["calendar"], conf="H", n="New `calendar.calendar` model in CE `calendar`", p=[r"calendar\.calendar"]),
    246: dict(s="ce", ce=["partner_autocomplete", "crm_iap_enrich"], conf="H", n="IAP enrichment service (credits)", p=[r"action_enrich"]),
    249: dict(s="ce", ce=["crm"], conf="H", p=[r"Always in rotation"]),
    251: dict(s="ce", ce=["crm"], conf="M", p=[r"TeamSwitcher|team_switcher|pipeline.*switch"]),
    253: dict(s="partial", ce=["hr_timesheet"], ee=["sale_timesheet_enterprise"], conf="M", n="Billing-target data in CE; the Timesheets dashboard analysis is EE", p=[r"billing.*target|billable_time_target"]),
    262: dict(s="ce", ce=["mail"], conf="H", p=[r"discuss\.category|channel.*categor"]),
    263: dict(s="ce", ce=["mail"], conf="M"),
    264: dict(s="ce", ce=["mail"], conf="H", p=[r"set_message_unread|mark_unread"]),
    265: dict(s="ce", ce=["mail"], conf="H", p=[r"discuss\.poll|mail\.poll|_name = .*poll"]),
    277: dict(s="ce", ce=["website_sale", "product"], conf="M", n="Cross-sell generation code is in CE `website_sale` (not in an AI module)", p=[r"cross.?sell"]),
    326: dict(s="ce", ce=["mass_mailing", "social_media"], conf="M", n="Uses the CE `social_media` links; the EE Social app is not required"),
    333: dict(s="ce", ce=["sale", "website_sale"], conf="M", p=[r"combo.*event|event.*combo"]),
    335: dict(s="ce", ce=["hr_expense"], conf="H", p=[r"expense.*limit|limit.*expense"]),
    346: dict(s="ce", ce=["stock", "purchase_stock"], conf="M", n="Inter-company resupply routes in CE `stock`", p=[r"inter.?company.*route|resupply"]),
    359: dict(s="ce", ce=["stock", "purchase_stock"], conf="M"),
    367: dict(s="ee", ee=["mrp_maintenance", "maintenance_enterprise"], conf="H", n="Gantt views are EE", p=[r"maintenance.*gantt|gantt.*maintenance"]),
    469: dict(s="ee", ee=["pos_appointment"], conf="H", p=[r"pos.*booking|booking.*pos"]),
    493: dict(s="ce", ce=["project", "project_account", "sale_project"], conf="M", n="Profitability panel removed from the project dashboard in favour of dedicated reports"),
    539: dict(s="ce", ce=["sale", "purchase_edi_ubl_bis3", "account_edi_ubl_cii"], conf="M"),
    603: dict(s="ce", ce=["base_automation", "mail"], conf="M", n="Automation rules are CE (`base_automation`); Studio only exposes them", p=[r"activity_plan"]),
    85: dict(s="partial", ce=["account"], ee=["account_followup"], conf="M", n="Invoice reminder sending in CE `account`; follow-up levels/automation EE", p=[r"invoice_reminder|send_reminder"]),
}
for _k, _v in _upd3.items():
    O[_k] = {"p": O.get(_k, {}).get("p", []), "ev": O.get(_k, {}).get("ev", []), **_v}

# probes for items whose override was set without one
for _k, _rx in {617: r"activitywatch", 72: r"account\.reconcile\.wizard", 78: r"_predict_", 100: r"pain\.001", 11: r"share_target",
                26: r"offline", 28: r"pinned_at", 97: r"XCG", 101: r"parent_id.*account\.account|account\.account.*parent_id",
                103: r"\bgln\b|global_location", 81: r"hash.*cash|cash.*hash", 261: r"transcri", 366: r"messenger|instagram",
                521: r"commission", 618: r"\btimer\b", 681: r"whatsapp", 39: r"Translation Mode", 21: r"material.symbols|MaterialSymbols"}.items():
    O.setdefault(_k, {}).setdefault("p", [])
    if _rx not in O[_k]["p"]:
        O[_k]["p"] = O[_k]["p"] + [_rx]

# ---- iteration 4: access-rights model change (runbot + source) ----
O[35] = dict(s="ce", ce=["base"], conf="H", t=["change"], p=[r"_name = .ir\.access."],
             n="`ir.model.access` and `ir.rule` are replaced by one `ir.access` model (model, group, operation, domain); modules ship "
               "`security/ir.access.csv`. Odoo provides `odoo/upgrade_code/19.4-00-ir-access.py` to convert module sources",
             ev=["runbot CE (API): model ir.model.access does not exist; ir.access exists (base, mail, website)",
                 "CE source: odoo/addons/base/models/ir_access.py; 226 CE modules ship security/ir.access.csv, 0 ship ir.model.access.csv"])

# ---- iteration 5: items that are a loss for Community users (tag "downside") ----
O[493] = dict(s="partial", ce=["project_account", "sale_project_margin", "project"], ee=["account_budget"], conf="M", t=["change", "downside"], p=[r"profitability"],
              n="The profitability panel is gone from the project dashboard. Margin reporting stays in CE (`project_account`, `sale_project_margin`); budget analysis needs EE `account_budget`")
O[291]["t"] = ["change", "downside"]
O[163] = dict(t=["change", "downside"], ev=["module diff 19.0→20.0: l10n_tr_nilvera, l10n_tr_nilvera_einvoice, l10n_tr_nilvera_edispatch removed from CE and present in the EE 20.0 source"])
